# Generated by Django 2.1.3 on 2019-01-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_menu_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='score',
            field=models.FloatField(verbose_name='评分'),
        ),
    ]
