# Generated by Django 2.1.3 on 2019-01-10 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_mtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamic',
            options={'verbose_name_plural': '动态管理'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='u_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='d',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kitchen.Dynamic', verbose_name='被评论者ID'),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='img',
            field=models.ImageField(default='', upload_to='', verbose_name='发布图片'),
        ),
    ]
