# Generated by Django 2.1.3 on 2019-01-11 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitchen', '0010_auto_20190111_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoucang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_id', models.BooleanField(default=False, verbose_name='是否删除')),
                ('user', models.CharField(max_length=200, verbose_name='用户')),
                ('c', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏菜谱')),
            ],
            options={
                'verbose_name_plural': '用户收藏',
            },
        ),
    ]
