# Generated by Django 2.1.3 on 2019-01-11 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0011_shoucang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoucang',
            name='c',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kitchen.Menu', verbose_name='收藏菜谱'),
        ),
    ]
