# Generated by Django 2.1.3 on 2019-01-14 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0012_auto_20190111_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dianzan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_id', models.BooleanField(default=False, verbose_name='是否删除')),
                ('user', models.CharField(max_length=200, verbose_name='用户')),
                ('c', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kitchen.Menu', verbose_name='点赞对象')),
            ],
            options={
                'verbose_name_plural': '点赞',
            },
        ),
        migrations.AlterModelOptions(
            name='guanzhu',
            options={'verbose_name_plural': '关注'},
        ),
        migrations.RemoveField(
            model_name='guanzhu',
            name='c',
        ),
        migrations.AlterField(
            model_name='guanzhu',
            name='s',
            field=models.CharField(default='', max_length=20, verbose_name='关注对象'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(default='', upload_to='img/', verbose_name='头像'),
        ),
    ]
